// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Passly.Persistence;

#nullable disable

namespace Passly.Persistence.Migrations.Modeling
{
    [DbContext(typeof(ModelingDbContext))]
    [Migration("20260218141146_AddSubmissionSummaries")]
    partial class AddSubmissionSummaries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("modeling")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Passly.Persistence.Models.Modeling.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("submissions", "modeling");
                });

            modelBuilder.Entity("Passly.Persistence.Models.Modeling.SubmissionSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatImportId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedPdf")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("GapCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("SelectedMessages")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("submission_summaries", "modeling");
                });

            modelBuilder.Entity("Passly.Persistence.Models.Modeling.SubmissionSummary", b =>
                {
                    b.HasOne("Passly.Persistence.Models.Modeling.Submission", "Submission")
                        .WithOne("Summary")
                        .HasForeignKey("Passly.Persistence.Models.Modeling.SubmissionSummary", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Passly.Persistence.Models.Modeling.Submission", b =>
                {
                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
