// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Passly.Persistence;
using Pgvector;

#nullable disable

namespace Passly.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Passly.Persistence.Models.ChatImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedRawContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FileHash")
                        .IsUnique();

                    b.ToTable("chat_imports", "app");
                });

            modelBuilder.Entity("Passly.Persistence.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatImportId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptedSenderName")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("MessageIndex")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatImportId");

                    b.HasIndex("ChatImportId", "Timestamp");

                    b.ToTable("chat_messages", "app");
                });

            modelBuilder.Entity("Passly.Persistence.Models.ChatMessageEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId")
                        .IsUnique();

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("chat_message_embeddings", "app");
                });

            modelBuilder.Entity("Passly.Persistence.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("submissions", "app");
                });

            modelBuilder.Entity("Passly.Persistence.Models.SubmissionSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatImportId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("ContentIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ContentSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ContentTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptedPdf")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptedSignature")
                        .HasColumnType("bytea");

                    b.Property<int>("GapCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Iv")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea");

                    b.Property<int>("SelectedMessages")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SignatureIv")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SignatureSalt")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SignatureTag")
                        .HasColumnType("bytea");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Tag")
                        .HasColumnType("bytea");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatImportId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("submission_summaries", "app");
                });

            modelBuilder.Entity("Passly.Persistence.Models.ChatImport", b =>
                {
                    b.HasOne("Passly.Persistence.Models.Submission", "Submission")
                        .WithMany("ChatImports")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Passly.Persistence.Models.ChatMessage", b =>
                {
                    b.HasOne("Passly.Persistence.Models.ChatImport", "ChatImport")
                        .WithMany("Messages")
                        .HasForeignKey("ChatImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatImport");
                });

            modelBuilder.Entity("Passly.Persistence.Models.ChatMessageEmbedding", b =>
                {
                    b.HasOne("Passly.Persistence.Models.ChatMessage", "ChatMessage")
                        .WithOne("Embedding")
                        .HasForeignKey("Passly.Persistence.Models.ChatMessageEmbedding", "ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("Passly.Persistence.Models.SubmissionSummary", b =>
                {
                    b.HasOne("Passly.Persistence.Models.ChatImport", "ChatImport")
                        .WithMany()
                        .HasForeignKey("ChatImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Passly.Persistence.Models.Submission", "Submission")
                        .WithOne("Summary")
                        .HasForeignKey("Passly.Persistence.Models.SubmissionSummary", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatImport");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Passly.Persistence.Models.ChatImport", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Passly.Persistence.Models.ChatMessage", b =>
                {
                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("Passly.Persistence.Models.Submission", b =>
                {
                    b.Navigation("ChatImports");

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
